# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/mubu_creat.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseMubuLogin(HttpRunner):
    config = Config("testcase description") \
        .variables(**
                   {
                       "host": "mubu.com",
                       "phone": "15070711714",
                       "password": "ying775825",
                   }) \
        .base_url("https://${host}") \
        .export('JwtToken','host')\
        .verify(False)

    teststeps = [
        Step(
            RunRequest("/")
                .get("/")
                .with_headers(
                **{
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"',
                    "sec-ch-ua-mobile": "?0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4412.3 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "none",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
                .with_cookies(
                **{
                    "data_unique_id": "d70f383c-a291-4bba-9e42-5ef5e152d9dd",
                    "reg_from": "https%3A%2F%2Fwww.baidu.com%2Flink%3Furl%3DSk2ayR2eBy-dWAxaxlU_Fri2bQ1nEonI7u01IMRRQbW%26wd%3D%26eqid%3Df4ef02d700702e7c00000004602d2e07",
                    "reg_entrance": "https%3A%2F%2F${host}%2Fapps",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1613573651",

                    "language": "en-US",
                    "country": "US",
                    "reg_prepareId": "177b3fd5311-177b3fd5308-44b1-91a1-b66eca97a7e2",
                    "reg_focusId": "e150640c-939d-44b1-91a1-177b3fd587e",
                    "SLARDAR_WEB_ID": "01f92bac-5b0b-4612-bdba-c26266b6232b",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1613634608",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/login")
                .get("/login")
                .with_headers(
                **{
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"',
                    "sec-ch-ua-mobile": "?0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4412.3 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
                .with_cookies(
                **{
                    "data_unique_id": "d70f383c-a291-4bba-9e42-5ef5e152d9dd",
                    "reg_from": "https%3A%2F%2Fwww.baidu.com%2Flink%3Furl%3DSk2ayR2eBy-dWAxaxlU_Fri2bQ1nEonI7u01IMRRQbW%26wd%3D%26eqid%3Df4ef02d700702e7c00000004602d2e07",
                    "reg_entrance": "https%3A%2F%2F${host}%2Fapps",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1613573651",

                    "language": "en-US",
                    "country": "US",
                    "reg_prepareId": "177b3fd5311-177b3fd5308-44b1-91a1-b66eca97a7e2",
                    "reg_focusId": "e150640c-939d-44b1-91a1-177b3fd587e",
                    "SESSION": "96ab81c0-9844-4141-a865-85c58d207dac",
                    "csrf_token": "2cd5ce59-0e1a-4b8f-8e08-30282820a5f4",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1613634926",
                    "SLARDAR_WEB_ID": "40075462-12b4-4785-bf2e-1d48a3c63cd8",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/login/password")
                .get("/login/password")
                .with_headers(
                **{
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"',
                    "sec-ch-ua-mobile": "?0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4412.3 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://${host}/login",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
                .with_cookies(
                **{
                    "data_unique_id": "d70f383c-a291-4bba-9e42-5ef5e152d9dd",
                    "reg_from": "https%3A%2F%2Fwww.baidu.com%2Flink%3Furl%3DSk2ayR2eBy-dWAxaxlU_Fri2bQ1nEonI7u01IMRRQbW%26wd%3D%26eqid%3Df4ef02d700702e7c00000004602d2e07",
                    "reg_entrance": "https%3A%2F%2F${host}%2Fapps",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1613573651",

                    "language": "en-US",
                    "country": "US",
                    "SESSION": "96ab81c0-9844-4141-a865-85c58d207dac",
                    "csrf_token": "2cd5ce59-0e1a-4b8f-8e08-30282820a5f4",

                    "reg_prepareId": "177b4234506-177b42344fd-4afe-ac86-b23cca827c63",
                    "SLARDAR_WEB_ID": "ea75c958-cc9d-493f-9497-244120a75f89",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1613634946",
                    "reg_focusId": "0a55ed66-78e8-4afe-ac86-177b4234b65",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/api/login/submit")
                .post("/api/login/submit")
                .with_headers(
                **{
                    "content-length": "51",
                    "sec-ch-ua": '" Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"',
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4412.3 Safari/537.36",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "en-US,en;q=0.9",
                }
            )
                .with_cookies(
                **{
                    "data_unique_id": "d70f383c-a291-4bba-9e42-5ef5e152d9dd",
                    "reg_from": "https%3A%2F%2Fwww.baidu.com%2Flink%3Furl%3DSk2ayR2eBy-dWAxaxlU_Fri2bQ1nEonI7u01IMRRQbW%26wd%3D%26eqid%3Df4ef02d700702e7c00000004602d2e07",
                    "reg_entrance": "https%3A%2F%2F${host}%2Fapps",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1613573651",

                    "language": "en-US",
                    "country": "US",
                    "SESSION": "96ab81c0-9844-4141-a865-85c58d207dac",
                    "csrf_token": "2cd5ce59-0e1a-4b8f-8e08-30282820a5f4",

                    "reg_prepareId": "177b4234506-177b42344fd-4afe-ac86-b23cca827c63",
                    "reg_focusId": "0a55ed66-78e8-4afe-ac86-177b4234b65",
                    "SLARDAR_WEB_ID": "d22b7f3e-ae00-4b0c-bd23-63c885d7fe40",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1613634949",
                }
            )
                .with_data(
                {"phone": "${phone}", "password": "${password}", "remember": "true"}
            )
                .extract()
                .with_jmespath('cookies."Jwt-Token"', "JwtToken")
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal("body.code", 0)
                .assert_equal("body.msg", None)
        )]

if __name__ == "__main__":
    TestCaseMubuLogin().test_start()